site_name: Lake Wingra Software Knowledge Base
theme: readthedocs
site_url: https://tdurtschi.github.io/lws-docs/
nav:
  - Home: index.md
  - TDD: tdd.md
  - Refactoring: refactoring.md
  - AI Links: ai-links.md
  - External Resources: good-stuff.md
  - Developer Experience: dev-experience.md
  - Docker: docker.md
  - .NET: dotnet.md
  - Git: git.md
  - Kubernetes: kubernetes.md
  - AI Art:
      - Birds on Bicycles: birds-on-bicycles.md
      - Birds on Bicycles II: birds-on-bicycles-ii.md
